spring.application.name=Komatoro
server.port=8080
debug=true
spring.profiles.active=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=DEBUG

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.acccess-token-key='{"kty":"oct","k":"asfgMthWBltjKyJn791rD38LKqirGhI8dWYEh_hzrWI"}'
jwt.refresh-token-key='{"kty":"oct","k":"HWS6epvQPr1R71__85JrI66ONrXJLQOnJT4vaRuOQjM"}'