POST http://localhost:8080/api/users/login/token
Authorization: Basic bWFpbEBtYWlsLnJ1OjEyMzQ1Njc=

###
POST http://localhost:8080/api/users/login/token
Content-Type: application/x-www-form-urlencoded

email=mail@mail.ru&password=1234567

###
GET http://localhost:8080/api/tasks
Authorization: Bearer eyJraWQiOiI1Y2E4M2IzNi04MjkxLTQ3Y2EtODI4NS01ZjBlNjg3YTAxYTYiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWlsQG1haWwucnUiLCJleHAiOjE3NzMyNTcxNTYsImlhdCI6MTc3MzI1NjI1NiwianRpIjoiNWNhODNiMzYtODI5MS00N2NhLTgyODUtNWYwZTY4N2EwMWE2IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl19.294hn7Ka2fr9eykalReP5adFdyzDbdFlhD-Nb_3_1_c

###
GET http://localhost:8080/api/sessions/all
Authorization: Bearer eyJraWQiOiIwZDcwNjllNy0xOTcxLTQxZDItOWU0OS01YjU5NGZjMTUzMjEiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..kWqZC5LAyLlFD36u.AwEOSy6jV_p4qexVLluqtmhfSS4onQgQc6brlhlM4yQr3FfMFnoWjKvf4UU4vYzaaPXxM2Rkivv33XDC0ffbIbgMhvYflfh9iqkEFKs4dnH5O6kiSLmniUJjRjnMmLlRyGfeIjkcMCIDqOMfSuabAb1jaqVoadu-Y9zGLEnGc3fxazxiGqvomekK-SYi9bxvkIEhcKv0RfaHziRIeLe80bxIqR9Y.2ljCr2VaIW4YpE9af4FVYg

###
POST http://localhost:8080/auth/refresh/token
Authorization: Bearer eyJraWQiOiI0OTIyODEzYy0xYTA2LTQ0MTItOWFhMi02MzhjNWE0NmI0MjgiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..bD8tD2KkdY5D1Bv6.M1SsrGQulmwCQFdGKYfMNQiZ_S8a1lqesdR_DGl0DR0MbPKAPR2wScYbgA-g0byDRN_vVx1WZdAHpLNBV2LdsYrlCc-YIBKEMsYp4Ly2BydTtqaYjmHLBX8i2Cl8CkzC1grcpdJ5POTVQ58ksPJpxzGpSPX7s988CApiR7_Xe7PFTh13vgIwiJcYHdqOdnCU-P9-rM26PQeU7Im2nvzhE29mIFnj.QymwMpsUudU7zXV0617B0A

###
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJraWQiOiIxYjBiNjA2MS1kMGY5LTQ1NDEtOGYwMy0wMTUwNWViYzZmMTMiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..jmTbu0y06WaJHxvz.msQy27q0G02NaBl-yPtpKIyUSUqAXhggB7OOrUY5Eg5Ui75pHS80tBNoEfNlNMvWSV1PiVAot9O4oTdUxy_Bo6b0nDkDaSQbvBN4l_2prLTsELvSHr_h1JTUkxhSU5Fl9mo0SbHIDqTHRm4nuDMA7XfK8tz9xqUSVu2GU9qcfZbrkXg7HKyptYmOzzMLkxhtSqKPyKooFXIldDoXEJ-EffZF9k90.3EvDx_lUpw8_8XM4ZSg9Iw
