create table users
(
    id bigint generated by default as identity primary key,
    username varchar(50) not null,
    password varchar(100) not null,
    email varchar(255) not null unique,
    role varchar(255) not null constraint users_role_check
        check (role IN ('USER', 'ADMIN')),
    verified boolean not null,
    created_at timestamp with time zone not null
);

create table user_settings
(
    id                    bigint generated by default as identity primary key,
    user_id               bigint not null unique,
    pomodoro_minutes      integer not null,
    long_break_minutes    integer not null,
    short_break_minutes   integer not null,
    long_break_interval   integer not null,

    constraint fk_user_settings_user foreign key (user_id) references users (id) on delete cascade,
    constraint chk_pomodoro_minutes check (pomodoro_minutes between 10 and 480),
    constraint chk_long_break_minutes check (long_break_minutes between 5 and 60),
    constraint chk_short_break_minutes check (short_break_minutes between 1 and 60),
    constraint chk_long_break_interval check (long_break_interval between 2 and 20)
);

create table user_daily_stats
(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    date date not null,
    focus_minutes integer not null,
    pomodoro_count integer not null,

    constraint fk_daily_stats_user foreign key (user_id) references users (id) on delete cascade,
    constraint uk_user_date unique (user_id, date),
    constraint chk_pomodoro_count check (pomodoro_count >= 0),
    constraint chk_focus_minutes check (focus_minutes >= 0)
);

create table tasks
(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(200) not null,
    description varchar(2000),
    is_active boolean not null,
    created_at timestamp(6) with time zone not null,

    constraint fk_tasks_user foreign key (user_id) references users (id) on delete cascade
);

create table tomato_sessions
(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    task_id bigint,
    created_at timestamp with time zone,
    type varchar(255)  not null,
    start_time timestamp with time zone not null,
    end_time timestamp with time zone,
    intended_minutes integer not null,
    status varchar(255) not null,
    total_active_minutes integer,
    last_resume_time timestamp with time zone,
    version bigint,

    constraint fk_tomato_sessions_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_tomato_sessions_task foreign key (task_id) references tasks (id) on delete set null,
    constraint chk_intended_minutes check (intended_minutes between 1 and 480),
    constraint chk_total_active_minutes check (total_active_minutes >= 0),
    constraint chk_tomato_type check (type in ('TASK', 'LONG_BREAK', 'SHORT_BREAK', 'TIMER')),
    constraint chk_tomato_status check (status in ('INTERRUPTED', 'COMPLETED', 'RUNNING', 'PAUSED'))
);

create index idx_tomato_session_user_id on tomato_sessions (user_id);
create index idx_tomato_session_status on tomato_sessions (status);
create index idx_tasks_user_id on tasks (user_id);